force-app/main/default/objects/Opportunity/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email_Status__c</fullName>
    <label>Invoice Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QB_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>The QuickBooks record Id.</inlineHelpText>
    <label>QB Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QB_Sync_Token__c.field-meta.xml
<CustomField>
    <fullName>QB_Sync_Token__c</fullName>
    <inlineHelpText>The QuickBooks Sync Token. This needs to stay in sync with QuickBooks in order to push information to QuickBooks.</inlineHelpText>
    <label>Sync Token</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Scheduled/Opportunity_QBSync.cls
public with sharing class Opportunity_QBSync implements Queueable, Database.AllowsCallouts {
    public class ScheduleSync implements Schedulable {
        //The scheduled class calls the queable as callouts are not allowed from scheduled jobs.
        public void execute(SchedulableContext SC) {
            System.enqueueJob(new Opportunity_QBSync());
        }
    }

    public static void schedulesync(){
        System.schedule('Invoice QB Sync', '0 0 0 * * ?', new ScheduleSync());
    }

    public void execute(QueueableContext context) {
        run();
    }

    public void run(){
        List<QBInvoice> invoices = (List<QBInvoice>)QBCallout.query('select * from Invoice', List<QBInvoice>.class, 'Invoice');
        System.debug(invoices);
        Map<String, Opportunity> oppByQBId = getOppsByQbId(invoices);

        List<Opportunity> updatedOpportunities = new List<Opportunity>();

        for (QBInvoice invoice : invoices) {
            if(oppByQBId.containsKey(invoice.Id) == false) {continue;}

            Opportunity opp = oppByQBId.get(invoice.Id);
            opp.QB_Id__c = invoice.Id;
            opp.QB_Sync_Token__c = invoice.SyncToken;
            opp.Balance__c = invoice.Balance;
            opp.Invoice_Email_Status__c = invoice.EmailStatus == 'EmailSent' ? 'Sent' : 'Not Sent';
            updatedOpportunities.add(opp);
        }

        update updatedOpportunities;
    }

    private Map<String, Opportunity> getOppsByQbId(List<QBInvoice> invoices) {
        Set<String> qbIds = new Set<String>();
        for (QBInvoice invoice : invoices) {
            qbIds.add(invoice.Id);
        }

        Map<String, Opportunity> opps = new Map<String, Opportunity>();
        for (Opportunity opp : [SELECT Id, Qb_Id__c FROM Opportunity WHERE Qb_Id__c IN :qbIds]) {
            opps.put(opp.QB_Id__c, opp);
        }

        return opps;
    }
}